name: Push-to-AWS-EC2

# Trigger deployment only on push to master branch 
on:
  push:
    branches:
      - test-patch-1

jobs:
  deploy:
    name: Deploy to AWS EC2 on test-patch-1 branch push ..
    runs-on: self-hosted

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
      
      - name: Move file to /var/www/html
        run: |
          cd ~
          mv ./actions-runner/_work/Magnetometer-Build /var/www/html
        
